# Generated by Django 4.0.2 on 2022-04-04 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_categoryuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryUser',
        ),
    ]
